// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/openapi/cluster/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// EnterpriseID mocks base method
func (m *MockRepository) EnterpriseID(eid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterpriseID", eid)
	ret0, _ := ret[0].(string)
	return ret0
}

// EnterpriseID indicates an expected call of EnterpriseID
func (mr *MockRepositoryMockRecorder) EnterpriseID(eid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterpriseID", reflect.TypeOf((*MockRepository)(nil).EnterpriseID), eid)
}
