// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/openapi/cluster/usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/goodrain/rainbond-operator/pkg/apis/rainbond/v1alpha1"
	cluster "github.com/goodrain/rainbond-operator/pkg/openapi/cluster"
	model "github.com/goodrain/rainbond-operator/pkg/openapi/model"
	v1 "github.com/goodrain/rainbond-operator/pkg/openapi/types/v1"
	v10 "k8s.io/api/core/v1"
	reflect "reflect"
)

// MockIClusterUcase is a mock of IClusterUcase interface
type MockIClusterUcase struct {
	ctrl     *gomock.Controller
	recorder *MockIClusterUcaseMockRecorder
}

// MockIClusterUcaseMockRecorder is the mock recorder for MockIClusterUcase
type MockIClusterUcaseMockRecorder struct {
	mock *MockIClusterUcase
}

// NewMockIClusterUcase creates a new mock instance
func NewMockIClusterUcase(ctrl *gomock.Controller) *MockIClusterUcase {
	mock := &MockIClusterUcase{ctrl: ctrl}
	mock.recorder = &MockIClusterUcaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIClusterUcase) EXPECT() *MockIClusterUcaseMockRecorder {
	return m.recorder
}

// GlobalConfigs mocks base method
func (m *MockIClusterUcase) GlobalConfigs() cluster.GlobalConfigUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalConfigs")
	ret0, _ := ret[0].(cluster.GlobalConfigUseCase)
	return ret0
}

// GlobalConfigs indicates an expected call of GlobalConfigs
func (mr *MockIClusterUcaseMockRecorder) GlobalConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalConfigs", reflect.TypeOf((*MockIClusterUcase)(nil).GlobalConfigs))
}

// Components mocks base method
func (m *MockIClusterUcase) Components() cluster.ComponentUsecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Components")
	ret0, _ := ret[0].(cluster.ComponentUsecase)
	return ret0
}

// Components indicates an expected call of Components
func (mr *MockIClusterUcaseMockRecorder) Components() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Components", reflect.TypeOf((*MockIClusterUcase)(nil).Components))
}

// Install mocks base method
func (m *MockIClusterUcase) Install() cluster.InstallUseCase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install")
	ret0, _ := ret[0].(cluster.InstallUseCase)
	return ret0
}

// Install indicates an expected call of Install
func (mr *MockIClusterUcaseMockRecorder) Install() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockIClusterUcase)(nil).Install))
}

// Cluster mocks base method
func (m *MockIClusterUcase) Cluster() cluster.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cluster")
	ret0, _ := ret[0].(cluster.Usecase)
	return ret0
}

// Cluster indicates an expected call of Cluster
func (mr *MockIClusterUcaseMockRecorder) Cluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cluster", reflect.TypeOf((*MockIClusterUcase)(nil).Cluster))
}

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Status mocks base method
func (m *MockUsecase) Status() (*model.ClusterStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(*model.ClusterStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status
func (mr *MockUsecaseMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockUsecase)(nil).Status))
}

// Init mocks base method
func (m *MockUsecase) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init
func (mr *MockUsecaseMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockUsecase)(nil).Init))
}

// UnInstall mocks base method
func (m *MockUsecase) UnInstall() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnInstall")
	ret0, _ := ret[0].(error)
	return ret0
}

// UnInstall indicates an expected call of UnInstall
func (mr *MockUsecaseMockRecorder) UnInstall() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnInstall", reflect.TypeOf((*MockUsecase)(nil).UnInstall))
}

// StatusInfo mocks base method
func (m *MockUsecase) StatusInfo() (*v1.ClusterStatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusInfo")
	ret0, _ := ret[0].(*v1.ClusterStatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatusInfo indicates an expected call of StatusInfo
func (mr *MockUsecaseMockRecorder) StatusInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusInfo", reflect.TypeOf((*MockUsecase)(nil).StatusInfo))
}

// ClusterNodes mocks base method
func (m *MockUsecase) ClusterNodes(query string, runGateway bool) []*v1.K8sNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterNodes", query, runGateway)
	ret0, _ := ret[0].([]*v1.K8sNode)
	return ret0
}

// ClusterNodes indicates an expected call of ClusterNodes
func (mr *MockUsecaseMockRecorder) ClusterNodes(query, runGateway interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterNodes", reflect.TypeOf((*MockUsecase)(nil).ClusterNodes), query, runGateway)
}

// CompleteNodes mocks base method
func (m *MockUsecase) CompleteNodes(nodes []*v1.K8sNode, runGateway bool) ([]*v1.K8sNode, []*v1.K8sNode) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteNodes", nodes, runGateway)
	ret0, _ := ret[0].([]*v1.K8sNode)
	ret1, _ := ret[1].([]*v1.K8sNode)
	return ret0, ret1
}

// CompleteNodes indicates an expected call of CompleteNodes
func (mr *MockUsecaseMockRecorder) CompleteNodes(nodes, runGateway interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteNodes", reflect.TypeOf((*MockUsecase)(nil).CompleteNodes), nodes, runGateway)
}

// MockGlobalConfigUseCase is a mock of GlobalConfigUseCase interface
type MockGlobalConfigUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalConfigUseCaseMockRecorder
}

// MockGlobalConfigUseCaseMockRecorder is the mock recorder for MockGlobalConfigUseCase
type MockGlobalConfigUseCaseMockRecorder struct {
	mock *MockGlobalConfigUseCase
}

// NewMockGlobalConfigUseCase creates a new mock instance
func NewMockGlobalConfigUseCase(ctrl *gomock.Controller) *MockGlobalConfigUseCase {
	mock := &MockGlobalConfigUseCase{ctrl: ctrl}
	mock.recorder = &MockGlobalConfigUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGlobalConfigUseCase) EXPECT() *MockGlobalConfigUseCaseMockRecorder {
	return m.recorder
}

// GlobalConfigs mocks base method
func (m *MockGlobalConfigUseCase) GlobalConfigs() (*model.GlobalConfigs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalConfigs")
	ret0, _ := ret[0].(*model.GlobalConfigs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalConfigs indicates an expected call of GlobalConfigs
func (mr *MockGlobalConfigUseCaseMockRecorder) GlobalConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalConfigs", reflect.TypeOf((*MockGlobalConfigUseCase)(nil).GlobalConfigs))
}

// UpdateGlobalConfig mocks base method
func (m *MockGlobalConfigUseCase) UpdateGlobalConfig(config *v1.GlobalConfigs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGlobalConfig", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGlobalConfig indicates an expected call of UpdateGlobalConfig
func (mr *MockGlobalConfigUseCaseMockRecorder) UpdateGlobalConfig(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGlobalConfig", reflect.TypeOf((*MockGlobalConfigUseCase)(nil).UpdateGlobalConfig), config)
}

// Address mocks base method
func (m *MockGlobalConfigUseCase) Address() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Address indicates an expected call of Address
func (mr *MockGlobalConfigUseCaseMockRecorder) Address() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockGlobalConfigUseCase)(nil).Address))
}

// MockComponentUsecase is a mock of ComponentUsecase interface
type MockComponentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockComponentUsecaseMockRecorder
}

// MockComponentUsecaseMockRecorder is the mock recorder for MockComponentUsecase
type MockComponentUsecaseMockRecorder struct {
	mock *MockComponentUsecase
}

// NewMockComponentUsecase creates a new mock instance
func NewMockComponentUsecase(ctrl *gomock.Controller) *MockComponentUsecase {
	mock := &MockComponentUsecase{ctrl: ctrl}
	mock.recorder = &MockComponentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockComponentUsecase) EXPECT() *MockComponentUsecaseMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockComponentUsecase) Get(name string) (*v1.RbdComponentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*v1.RbdComponentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockComponentUsecaseMockRecorder) Get(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockComponentUsecase)(nil).Get), name)
}

// List mocks base method
func (m *MockComponentUsecase) List(isInit bool) ([]*v1.RbdComponentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", isInit)
	ret0, _ := ret[0].([]*v1.RbdComponentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockComponentUsecaseMockRecorder) List(isInit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockComponentUsecase)(nil).List), isInit)
}

// ListComponents mocks base method
func (m *MockComponentUsecase) ListComponents() []*v1alpha1.RbdComponent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComponents")
	ret0, _ := ret[0].([]*v1alpha1.RbdComponent)
	return ret0
}

// ListComponents indicates an expected call of ListComponents
func (mr *MockComponentUsecaseMockRecorder) ListComponents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComponents", reflect.TypeOf((*MockComponentUsecase)(nil).ListComponents))
}

// ListPodsByComponent mocks base method
func (m *MockComponentUsecase) ListPodsByComponent(cpn *v1alpha1.RbdComponent) ([]*v10.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPodsByComponent", cpn)
	ret0, _ := ret[0].([]*v10.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPodsByComponent indicates an expected call of ListPodsByComponent
func (mr *MockComponentUsecaseMockRecorder) ListPodsByComponent(cpn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPodsByComponent", reflect.TypeOf((*MockComponentUsecase)(nil).ListPodsByComponent), cpn)
}

// MockInstallUseCase is a mock of InstallUseCase interface
type MockInstallUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInstallUseCaseMockRecorder
}

// MockInstallUseCaseMockRecorder is the mock recorder for MockInstallUseCase
type MockInstallUseCaseMockRecorder struct {
	mock *MockInstallUseCase
}

// NewMockInstallUseCase creates a new mock instance
func NewMockInstallUseCase(ctrl *gomock.Controller) *MockInstallUseCase {
	mock := &MockInstallUseCase{ctrl: ctrl}
	mock.recorder = &MockInstallUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstallUseCase) EXPECT() *MockInstallUseCaseMockRecorder {
	return m.recorder
}

// Install mocks base method
func (m *MockInstallUseCase) Install(req *v1.ClusterInstallReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install
func (mr *MockInstallUseCaseMockRecorder) Install(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockInstallUseCase)(nil).Install), req)
}

// InstallStatus mocks base method
func (m *MockInstallUseCase) InstallStatus() (model.StatusRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallStatus")
	ret0, _ := ret[0].(model.StatusRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallStatus indicates an expected call of InstallStatus
func (mr *MockInstallUseCaseMockRecorder) InstallStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallStatus", reflect.TypeOf((*MockInstallUseCase)(nil).InstallStatus))
}

// RestartPackage mocks base method
func (m *MockInstallUseCase) RestartPackage() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartPackage")
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartPackage indicates an expected call of RestartPackage
func (mr *MockInstallUseCaseMockRecorder) RestartPackage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartPackage", reflect.TypeOf((*MockInstallUseCase)(nil).RestartPackage))
}
