kind: pipeline
name: build arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
    - custom
node:
  city: sydney
steps:
- name: build operator
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    VERSION:
      from_secret: version
    GOOS: linux
    GOARCH: arm64
    DOCKER_BUILDKIT: 0
    COMPOSE_DOCKER_CLI_BUILD: 0
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build --build-arg ARCH=$GOARCH --build-arg GOPROXY="https://goproxy.cn" -t rainbond/rainbond-operator:$VERSION .
  - docker push rainbond/rainbond-operator:$VERSION
  when:
    event:
      include:
      - custom
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock