apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-worker
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-worker
    persistentVolumeClaimAccessModes: ReadWriteOnce
spec:
  env:
  - name: ALLINONE_MODE
    value: "true"
  - name: TCPMESH_DEFAULT_IMAGE_NAME
    value: "rainbond/rbd-mesh-data-panel:v5.6.0-release"
  - name: PROBE_MESH_IMAGE_NAME
    value: "rainbond/rbd-init-probe:v5.6.0-release"
  replicas: 1
  image: rainbond/rbd-worker:v5.6.0-release
  imagePullPolicy: IfNotPresent
  priorityComponent: false
  args:
  - --db-type=sqlite
  volumeMounts:
  - mountPath: /db
    name: sqlite
  volumes:
  - hostPath:
      path: /app/data
      type: DirectoryOrCreate
    name: sqlite
