apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-mq
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-mq
spec:
  replicas: 1
  image: rainbond/rbd-mq:v5.6.0-release
  imagePullPolicy: IfNotPresent
  priorityComponent: false
