apiVersion: wutong.io/v1alpha1
kind: WutongComponent
metadata:
  name: wt-etcd
  namespace: wt-system
  labels:
    belongTo: wutong-operator
    creator: Wutong
    name: wt-etcd
    priorityComponent: "true"
spec:
  replicas: 1
  image: swr.cn-southwest-2.myhuaweicloud.com/wutong/etcd:v3.3.18
  imagePullPolicy: IfNotPresent
  priorityComponent: true
