apiVersion: wutong.io/v1alpha1
kind: WutongComponent
metadata:
  name: wt-hub
  namespace: wt-system
  labels:
    belongTo: wutong-operator
    creator: Wutong
    name: wt-hub
    priorityComponent: "true"
    persistentVolumeClaimAccessModes: ReadWriteOnce
spec:
  replicas: 1
  image: swr.cn-southwest-2.myhuaweicloud.com/wutong/registry:2.6.2
  imagePullPolicy: Always
  priorityComponent: true
