{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    name: {{ .Values.serviceAccount.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

{{- end }}