
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - wutong.io
  resources:
  - WutongClusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wutong.io
  resources:
  - WutongClusters/finalizers
  verbs:
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongClusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongPackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wutong.io
  resources:
  - WutongPackages/finalizers
  verbs:
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongPackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongVolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wutong.io
  resources:
  - WutongVolumes/finalizers
  verbs:
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongVolumes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongComponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wutong.io
  resources:
  - WutongComponents/finalizers
  verbs:
  - update
- apiGroups:
  - wutong.io
  resources:
  - WutongComponents/status
  verbs:
  - get
  - patch
  - update
