# permissions for end users to edit wutongcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wutongcomponent-editor-role
rules:
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - wutongcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - wutongcomponents/status
  verbs:
  - get
