# permissions for end users to edit WutongClusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: WutongCluster-editor-role
rules:
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - WutongClusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - WutongClusters/status
  verbs:
  - get
