# permissions for end users to view wutongvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wutongvolume-viewer-role
rules:
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - wutongvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - wutongvolumes/status
  verbs:
  - get
