# permissions for end users to view wutongclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wutongcluster-viewer-role
rules:
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - wutongclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wutong.io.wutong.io
  resources:
  - wutongclusters/status
  verbs:
  - get
