// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/controller/rainbondcluster/pkg/install.go

// Package mock is a generated GoMock package.
package mock

import (
	types "github.com/GLYASAI/rainbond-operator/pkg/controller/rainbondcluster/types"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPackageInterface is a mock of PackageInterface interface
type MockPackageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPackageInterfaceMockRecorder
}

// MockPackageInterfaceMockRecorder is the mock recorder for MockPackageInterface
type MockPackageInterfaceMockRecorder struct {
	mock *MockPackageInterface
}

// NewMockPackageInterface creates a new mock instance
func NewMockPackageInterface(ctrl *gomock.Controller) *MockPackageInterface {
	mock := &MockPackageInterface{ctrl: ctrl}
	mock.recorder = &MockPackageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPackageInterface) EXPECT() *MockPackageInterfaceMockRecorder {
	return m.recorder
}

// MockHistoryInterface is a mock of HistoryInterface interface
type MockHistoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryInterfaceMockRecorder
}

// MockHistoryInterfaceMockRecorder is the mock recorder for MockHistoryInterface
type MockHistoryInterfaceMockRecorder struct {
	mock *MockHistoryInterface
}

// NewMockHistoryInterface creates a new mock instance
func NewMockHistoryInterface(ctrl *gomock.Controller) *MockHistoryInterface {
	mock := &MockHistoryInterface{ctrl: ctrl}
	mock.recorder = &MockHistoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHistoryInterface) EXPECT() *MockHistoryInterfaceMockRecorder {
	return m.recorder
}

// ExtractionHistory mocks base method
func (m *MockHistoryInterface) ExtractionHistory() (*types.ExtractionHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractionHistory")
	ret0, _ := ret[0].(*types.ExtractionHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractionHistory indicates an expected call of ExtractionHistory
func (mr *MockHistoryInterfaceMockRecorder) ExtractionHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractionHistory", reflect.TypeOf((*MockHistoryInterface)(nil).ExtractionHistory))
}
