module.exports = [
  { name: 'vue', library: 'Vue', js: './js/vue.js', css: '' },
  { name: 'vue-i18n', library: 'VueI18n', js: './js/vue-i18n.min.js', css: '' },
  { name: 'vue-router', library: 'VueRouter', js: './js/vue-router.min.js', css: '' },
  { name: 'vuex', library: 'Vuex', js: './js/vuex.min.js', css: '' },
  { name: 'axios', library: 'axios', js: './js/axios.min.js', css: '' },
  { name: 'better-scroll', library: 'BScroll', js: './js/bscroll.min.js', css: '' },
  { name: 'element-ui', library: 'ELEMENT', js: './js/element-ui.js', css: './css/element-ui.css' },
  { name: 'lodash', library: '_', js: './js/lodash.js', css: '' },
  { name: 'ua-parser-js', library: 'UAParser', js: './js/ua-parser.js', css: '' },
  { name: 'js-cookie', library: 'Cookies', js: './js/js-cookie.js', css: '' },
  { name: 'nprogress', library: 'NProgress', js: './js/nprogress.js', css: './css/nprogress.css' },
  { name: 'dayjs', library: 'dayjs', js: './js/dayjs.js', css: '' },
  { name: 'fuse.js', library: 'Fuse', js: './js/fuse.js', css: '' },
  { name: 'hotkeys-js', library: 'hotkeys', js: './js/hotkeys.js', css: '' },
  { name: 'qs', library: 'Qs', js: './js/qs.js', css: '' },
  { name: 'lowdb', library: 'low', js: './js/low.js', css: '' },
  { name: 'lowdb/adapters/LocalStorage', library: 'LocalStorage', js: './js/localStorage.js', css: '' },
  { name: 'screenfull', library: 'screenfull', js: './js/screenfull.js', css: '' },
  { name: 'sortablejs', library: 'Sortable', js: './js/sortable.js', css: '' }
]
